apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fist-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: first-app
    helm:
      parameters:
      - name: pvc.storage_size
        value: 200Mi
    repoURL: https://pluhin.github.io/helm-25-23/
    targetRevision: 0.2.0
  syncPolicy:
    syncOptions:
    - PruneLast=true
